version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - depguard
    - dogsled
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godox
    - lll
    - mnd
    - prealloc
    - wsl
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - performance
        - style
        - diagnostic
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/kelsos/rotki-sync
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
